*** Starting uWSGI 2.0.18 (64bit) on [Fri Jan  3 03:55:50 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 03 January 2020 03:43:33
os: Linux-3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
nodename: vm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/buhuai/ansibles
writing pidfile to uwsgi.pid
detected binary path: /data/env/pyweb/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /data/wwwroot/devops/
your processes number limit is 13625
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.6 (default, Jan  3 2020, 03:27:03)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Python main interpreter initialized at 0x272ae10
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x272ae10 pid: 47958 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 47958)
spawned uWSGI worker 1 (pid: 47971, cores: 1)
Python auto-reloader enabled
spawned uWSGI worker 2 (pid: 47973, cores: 1)
spawned uWSGI worker 3 (pid: 47974, cores: 1)
spawned uWSGI worker 4 (pid: 47975, cores: 1)
*** Stats server enabled on uwsgi.status fd: 19 ***
[pid: 47975|app: 0|req: 1/1] 167.220.232.102 () {48 vars in 781 bytes} [Fri Jan  3 03:57:30 2020] GET / => generated 148 bytes in 157 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 47975|app: 0|req: 2/2] 167.220.232.102 () {42 vars in 637 bytes} [Fri Jan  3 03:57:31 2020] GET /favicon.ico => generated 1966 bytes in 14 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 0)
[uwsgi-python-reloader] module/file ./devops/urls.py has been modified
...gracefully killing workers...
Gracefully killing worker 2 (pid: 47973)...
Gracefully killing worker 1 (pid: 47971)...
Gracefully killing worker 4 (pid: 47975)...
Gracefully killing worker 3 (pid: 47974)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/buhuai/ansibles
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /data/env/pyweb/bin/uwsgi
[uWSGI] parsing config file /data/wwwroot/devops/devops.xml
*** Starting uWSGI 2.0.18 (64bit) on [Fri Jan  3 04:30:48 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 03 January 2020 03:43:33
os: Linux-3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
nodename: vm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/buhuai/ansibles
detected binary path: /data/env/pyweb/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /data/wwwroot/devops/
your processes number limit is 13625
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.6 (default, Jan  3 2020, 03:27:03)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Python main interpreter initialized at 0x1f55cf0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1f55cf0 pid: 47958 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 47958)
spawned uWSGI worker 1 (pid: 53184, cores: 1)
spawned uWSGI worker 2 (pid: 53185, cores: 1)
spawned uWSGI worker 3 (pid: 53186, cores: 1)
spawned uWSGI worker 4 (pid: 53188, cores: 1)
Python auto-reloader enabled
*** Stats server enabled on uwsgi.status fd: 19 ***
[uwsgi-python-reloader] module/file /data/env/pyweb/lib/python3.6/site-packages/django/__init__.py has been modified
...gracefully killing workers...
Gracefully killing worker 1 (pid: 53184)...
Gracefully killing worker 3 (pid: 53186)...
Gracefully killing worker 2 (pid: 53185)...
Gracefully killing worker 4 (pid: 53188)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/buhuai/ansibles
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /data/env/pyweb/bin/uwsgi
[uWSGI] parsing config file /data/wwwroot/devops/devops.xml
*** Starting uWSGI 2.0.18 (64bit) on [Fri Jan  3 05:49:26 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 03 January 2020 03:43:33
os: Linux-3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
nodename: vm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/buhuai/ansibles
detected binary path: /data/env/pyweb/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /data/wwwroot/devops/
your processes number limit is 13625
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.6 (default, Jan  3 2020, 03:27:03)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Python main interpreter initialized at 0xed0cf0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./devops/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/data/env/pyweb/lib/python3.6/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
ModuleNotFoundError: No module named 'django.utils'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 47958)
spawned uWSGI worker 1 (pid: 56909, cores: 1)
spawned uWSGI worker 2 (pid: 56910, cores: 1)
spawned uWSGI worker 3 (pid: 56911, cores: 1)
spawned uWSGI worker 4 (pid: 56912, cores: 1)
*** Stats server enabled on uwsgi.status fd: 15 ***
Python auto-reloader enabled
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xed0cf0 pid: 56910 (default app)
/data/env/pyweb/lib/python3.6/site-packages/pandas/compat/__init__.py:85: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
[pid: 56910|app: 0|req: 1/1] 167.220.232.102 () {44 vars in 792 bytes} [Fri Jan  3 05:50:45 2020] GET / => generated 9967 bytes in 3234 msecs (HTTP/1.1 200) 6 headers in 319 bytes (1 switches on core 0)
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xed0cf0 pid: 56909 (default app)
/data/env/pyweb/lib/python3.6/site-packages/pandas/compat/__init__.py:85: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Not Found: /favicon.ico
[pid: 56909|app: 0|req: 1/2] 167.220.232.102 () {46 vars in 819 bytes} [Fri Jan  3 05:50:49 2020] GET /favicon.ico => generated 2346 bytes in 3142 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 0)
